/* Project */
export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCEED = 'CREATE_JOB_SUCCEED';
export const CREATE_JOB_FAILED = 'CREATE_JOB_FAILED';

export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_SUCCEED = 'UPDATE_JOB_SUCCEED';
export const UPDATE_JOB_FAILED = 'UPDATE_JOB_FAILED';
