export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_SUCCEED = 'FETCH_PROJECTS_SUCCEED';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_SUCCEED = 'CREATE_PROJECT_SUCCEED';
export const CREATE_PROJECT_FAILED = 'CREATE_PROJECT_FAILED';

export const RESET_NOTIFICATION_STATE = 'RESET_NOTIFICATION_STATE';
