export const CHECK_AUTH_REQUEST = 'CHECK_AUTH_REQUEST';
export const CHECK_AUTH_REQUEST_SUCCEED = 'CHECK_AUTH_REQUEST_SUCCEED';
export const CHECK_AUTH_REQUEST_FAILED = 'CHECK_AUTH_REQUEST_FAILED';

export const FETCH_ALL_USER_ACCOUNTS = 'FETCH_ALL_USER_ACCOUNTS';
export const FETCH_ALL_USER_ACCOUNTS_SUCCEED = 'FETCH_ALL_USER_ACCOUNTS_SUCCEED';
export const FETCH_ALL_USER_ACCOUNTS_FAILED = 'FETCH_ALL_USER_ACCOUNTS_FAILED';

export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
