/* Project */
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const FETCH_PROJECT_SUCCEED = 'FETCH_PROJECT_SUCCEED';
export const FETCH_PROJECT_FAILED = 'FETCH_PROJECT_FAILED';

export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_SUCCEED = 'UPDATE_PROJECT_SUCCEED';
export const UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED';

export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_SUCCEED = 'DELETE_PROJECT_SUCCEED';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';

/* Jobs */
export const FETCH_ALL_JOBS = 'FETCH_ALL_JOBS';
export const FETCH_ALL_JOBS_SUCCEED = 'FETCH_ALL_JOBS_SUCCEED';
export const FETCH_ALL_JOBS_FAILED = 'FETCH_ALL_JOBS_FAILED';

export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCEED = 'CREATE_JOB_SUCCEED';
export const CREATE_JOB_FAILED = 'CREATE_JOB_FAILED';

export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_SUCCEED = 'UPDATE_JOB_SUCCEED';
export const UPDATE_JOB_FAILED = 'UPDATE_JOB_FAILED';

export const DELETE_JOB = 'DELETE_JOB';
export const DELETE_JOB_SUCCEED = 'DELETE_JOB_SUCCEED';
export const DELETE_JOB_FAILED = 'DELETE_JOB_FAILED';

/* Team members */
export const FETCH_ALL_TEAM_MEMBERS = 'FETCH_ALL_TEAM_MEMBERS';
export const FETCH_ALL_TEAM_MEMBERS_SUCCEED = 'FETCH_ALL_TEAM_MEMBERS_SUCCEED';
export const FETCH_ALL_TEAM_MEMBERS_FAILED = 'FETCH_ALL_TEAM_MEMBERS_FAILED';

export const INVITE_TEAM_MEMBERS = 'INVITE_TEAM_MEMBERS';
export const INVITE_TEAM_MEMBERS_SUCCEED = 'INVITE_TEAM_MEMBERS_SUCCEED';
export const INVITE_TEAM_MEMBERS_FAILED = 'INVITE_TEAM_MEMBERS_FAILED';

export const REMOVE_TEAM_MEMBER = 'REMOVE_TEAM_MEMBER';
export const REMOVE_TEAM_MEMBER_SUCCEED = 'REMOVE_TEAM_MEMBER_SUCCEED';
export const REMOVE_TEAM_MEMBER_FAILED = 'REMOVE_TEAM_MEMBER_FAILED';
