export const TEST_REQUEST = 'TEST_REQUEST';
export const TEST_REQUEST_SUCCEED = 'TEST_REQUEST_SUCCEED';
export const TEST_REQUEST_FAILED = 'TEST_REQUEST_FAILED';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCEED = 'SIGNUP_SUCCEED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const CONFIRM_EMAIL = 'CONFIRM_EMAIL';
export const CONFIRM_EMAIL_SUCCEED = 'CONFIRM_EMAIL_SUCCEED';
export const CONFIRM_EMAIL_FAILED = 'CONFIRM_EMAIL_FAILED';
